#!/usr/bin/env ruby
require 'net/http'
require 'uri'
require 'json'
#List Applications
ak='83e1c51dd6d9e3a3a608b52d733892db0e9bd9a6d18bd0c'
#Get request sample
def getRequest(ak,uri,host,path)
  uri=URI.parse(uri)
  headers = {
           "X-Api-Key" => ak
            }
  host=uri.host
  path=uri.path
  http = Net::HTTP.new(uri.host, uri.port)
  http.use_ssl = true
  res,req = http.get(path,headers)
  puts JSON.pretty_generate(res.body)
end
#getApplications(ak)
#curl -X GET 'https://api.newrelic.com/v2/applications.json' \-H 'X-Api-Key:83e1c51dd6d9e3a3a608b52d733892db0e9bd9a6d18bd0c' -i
def getApplications(ak)
  uri='https://api.newrelic.com/v2/applications.json'
  parseUrl=URI.parse(uri)
  host=parseUrl.host
  path=parseUrl.path
  getRequest(ak,uri,host,path)
end
#DOCUMENT HTML
puts "Content-type: text/html\n\n"
puts ""
puts ""
getApplications(ak)
